---
- name: Deploy abc-tech-pro
  hosts: all
  become: true
  tasks:
    - name: Create Deployment
      kubernetes.core.v1beta1.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-tech-pro
          spec:
            selector:
              matchLabels:
                app: abc-tech-pro
            replicas: 2
            template:
              metadata:
                labels:
                  app: abc-tech-pro
              spec:
                containers:
                  - name: abc-tech-pro
                    image: majormekzy/abc_technologies:latest
                    command:
                      - /bin/sh
                      - -c
                      - sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done
                    ports:
                      - name: http
                        containerPort: 8080
    - name: Create Service
      kubernetes.core.v1.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: abc-tech-pro-service
            labels:
              app: abc-tech-pro
          spec:
            type: NodePort
            ports:
              - port: 8080
                nodePort: 31884
                protocol: TCP
                name: http
            selector:
              app: abc-tech-pro
---
