apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-pro
  labels:
    app: abc-tech-pro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-tech-pro
  template:
    metadata:
      labels:
        app: abc-tech-pro
    spec:
      containers:
      - name: abc-tech-pro
        image: majormekzy/abc_technologies:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: abc-tech-app-services
spec:
  type: NodePort
  selector:
    app: abc-tech-pro
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
