kind: Deployment
apiVersion: apps/v1
metadata:
  name: abc-tech-app
spec:
  replicas: 2
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: abc-tech-app
  template:
    metadata:
      labels:
        app: abc-tech-app
    spec:
      containers:
        - name: app
          image: majormekzy/abc_technologies:latest
---
kind: Service
apiVersion: v1
metadata:
  name: abc-tech-app-services
spec:
  type: NodePort
  selector:
    app: abc-tech-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32000
